### ISSUE TITLE
ERROR when export to ONNX

### ISSUE THREAD

**Issue by niuwenju** [open-edge-platform/geti#174]
Done (t=0.40s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/dc/anaconda3/lib/python3.6/pydoc.py", line 343, in safeimport
    module = __import__(path)
  File "/home/dc/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/model_zoo/resnet_fpn_mask_rcnn.py", line 19, in <module>
    from .fpn_mask_rcnn_base import FPNMaskRCNN, BboxHead, DetectionOutput, MaskHead
  File "/home/dc/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/model_zoo/fpn_mask_rcnn_base.py", line 29, in <module>
    from ..roi_feature_extractor import extract_roi_features, topk_rois
  **File "/home/dc/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/roi_feature_extractor.py", line 19, in <module>
    from .roi_align import roi_align
  File "/home/dc/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/roi_align.py", line 20, in <module>
    from ..extensions._EXTRA import roi_align_forward, roi_align_backward
ModuleNotFoundError: No module named 'segmentoly.extensions._EXTRA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/convert_to_onnx.py", line 87, in <module>
    main(args)
  File "tools/convert_to_onnx.py", line 64, in main
    net = locate(args.model)(classes_num, fc_detection_head=False)
  File "/home/dc/anaconda3/lib/python3.6/pydoc.py", line 1581, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/home/dc/anaconda3/lib/python3.6/pydoc.py", line 358, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in segmentoly.rcnn.model_zoo.resnet_fpn_mask_rcnn - ModuleNotFoundError: No module named 'segmentoly.extensions._EXTRA'**

when i export mask_rcnn_resnet50_fpn_2x.pth to ONNX,I  got this error.

Environment:
 - OS: Linux Ubuntu 18.04
 - Framework version: PyTorch==0.4.1
 - Python version:3.6
 - OpenVINO version: 2019_R3.1

**Comment by Ilya-Krylov** [comment]
Segmentoly does not exist anymore, please have a look at recently added instance segmentation models https://github.com/openvinotoolkit/training_extensions#models
