### ISSUE TITLE
NNCF export to ONNX fails

### ISSUE THREAD

**Issue by miikargh** [open-edge-platform/geti#293]
**Describe the bug**

Trying to export a  compressed model to onnx and I get the following error:
```bash
Traceback (most recent call last):
  File "onnx_example.py", line 13, in <module>
    compressed_model.export_model("/models/compressed_model.onnx")
  File "/openvino_training_extensions/pytorch_toolkit/nncf/nncf/nncf_network.py", line 443, in __getattr__
    return super().__getattr__(name)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'NNCFNetwork' object has no attribute 'export_model'
```

**Steps to Reproduce**

1. Install the latest version of  NNCF
2. Run the following code
```python
import nncf
from nncf import create_compressed_model, Config as NNCFConfig

# Instantiate your uncompressed model
from torchvision.models.resnet import resnet50

model = resnet50()

# Apply compression according to a loaded NNCF config
nncf_config = NNCFConfig.from_json("./resnet_rb_sparsity_int8.json")
comp_ctrl, compressed_model = create_compressed_model(model, nncf_config)

compressed_model.export_model("/models/compressed_model.onnx")
```

**Environment:**
Dockerfile along with all necessary steps to reproduce found here: https://github.com/miikargh/nncf_issue

**Comment by AlexanderDokuchaev** [comment]
@AlexKoff88 @vshampor @ljaljushkin

**Comment by vshampor** [comment]
Greetings, @miikargh!

This is a mistake in the documentation. Use `comp_ctrl.export_model("/models/compressed_model.onnx")` instead.
