### ISSUE TITLE
AssertionError: Scores blob contains NaN values.

### ISSUE THREAD

**Issue by Zoushuang86** [open-edge-platform/geti#356]
When I used the coco2017 dataset to train the instance segmentation model, the following problems occurred.

INFO 24-10-20 13:53:20 train.py: 118] Called with args: 
 -batch_size: 16
 -load_cfg: None
 -num_workers: 4
 -save_cfg: None
 -max_iter: 90000
 -load_backbone: None
 -mean_pixel: (102.9801, 115.9465, 122.7717)
 -checkpoint_interval: 10000
 -dataset: coco2017
 -warmup_iters: 1000
 -test_interval: 10000
 -output_dir: /home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/tools/../outputs
 -lr: 0.02
 -gamma: 0.1
 -model: segmentoly.rcnn.model_zoo.resnet_fpn_mask_rcnn.ResNet50FPNMaskRCNN
 -batch_size_per_gpu: 2
 -resume: False
 -weight_decay: 0.0001
 -warmup_method: linear
 -momentum: 0.9
 -max_image_size: (800, 1333)
 -display_interval: 20
 -drop_lr: (60000, 80000)
 -warmup_factor: 0.33
 -load_ckpt: None
INFO 24-10-20 13:53:20 training_engine.py: 133] Virtual iter size set to 8
INFO 24-10-20 13:53:20 training_engine.py: 134] Effective batch size 16
loading annotations into memory...
Done (t=0.99s)
creating index...
index created!
loading annotations into memory...
Done (t=0.72s)
creating index...
index created!
INFO 24-10-20 13:53:23 training_engine.py: 284] Using 1 GPUs for training
INFO 24-10-20 13:53:25 training_engine.py:  69] save model to "/home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/tools/../outputs/MaskRCNN/Oct24-13-53-20/ckpt/model_step_0.pth"
INFO 24-10-20 13:53:25 training_engine.py: 301] Start training...
INFO 24-10-20 13:53:29 logging.py:  99] Step 0 / 90000, lr: 0.0066, loss: 11323.1
  losses/TOTAL: 11323.1, losses/detection/cls: 4875.31, losses/detection/reg: 13.068, losses/mask: 5803.04, losses/rpn: 631.687, 
  losses/rpn/cls: 361.117, losses/rpn/cls/0: 230.248, losses/rpn/cls/1: 106.025, losses/rpn/cls/2: 16.499, losses/rpn/cls/3: 5.88191, 
  losses/rpn/cls/4: 2.46316, losses/rpn/reg: 270.571, losses/rpn/reg/0: 50.0775, losses/rpn/reg/1: 23.2202, losses/rpn/reg/2: 43.7754, 
  losses/rpn/reg/3: 58.2225, losses/rpn/reg/4: 95.275, metrics/detection/cls_accuracy: 0.0, metrics/rpn/cls_accuracy/0: 0.34434, 
  metrics/rpn/cls_accuracy/1: 0.10136, metrics/rpn/cls_accuracy/2: 0.581589, metrics/rpn/cls_accuracy/3: 0.511506, 
  metrics/rpn/cls_accuracy/4: nan, metrics/rpn/cls_precision/0: 0.0222074, metrics/rpn/cls_precision/1: 0.0517144, 
  metrics/rpn/cls_precision/2: nan, metrics/rpn/cls_precision/3: 0.538393, metrics/rpn/cls_precision/4: nan, metrics/rpn/cls_recall/0: nan, 
  time elapsed/~left: 0:00:00 / 0:00:00 (0.0 sec/it)
Traceback (most recent call last):
  File "tools/train.py", line 216, in <module>
    main(args)
  File "tools/train.py", line 210, in main
    train_tool.run(start_step)
  File "/home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/utils/training_engine.py", line 323, in run
    minibatch_metrics, loss = model(**data_batch)
  File "/home/anna/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anna/anaconda3/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/anna/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/utils/profile.py", line 106, in wrapper_timer
    value = func(self, *args, **kwargs)
  File "/home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/model_zoo/fpn_mask_rcnn_base.py", line 276, in forward
    rpn_cls_targets, rpn_reg_targets, batch_size)
  File "/home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/utils/profile.py", line 106, in wrapper_timer
    value = func(self, *args, **kwargs)
  File "/home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/model_zoo/fpn_mask_rcnn_base.py", line 398, in forward_rpn
    force_max_output_size=self.force_max_output_size)
  File "/home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/proposal.py", line 42, in generate_proposals
    nms_threshold, min_size, force_max_output_size)
  File "/home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/proposal.py", line 139, in forward
    force_max_output_size)
  File "/home/anna/myfiles/code/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/proposal.py", line 67, in generate_proposals_single_image
    assert not torch.isnan(scores).any(), 'Scores blob contains NaN values.'
AssertionError: Scores blob contains NaN values.

Do you know how to overcome this issue ?

Thank you in advance !

**Comment by druzhkov-paul** [comment]
@Zoushuang86 Training from scratch (i.e. randomly initialized weights) might be tricky, and you should at least adjust learning rate properly and make sure that none of the layers are frozen. Otherwise, optimization procedure involved in training will diverge, producing infinite loss values, like in your logs. Common approach to training such networks is to initialize backbone part of the network with weights of a corresponding ImageNet classifier. Please specify corresponding weights file via a `--load_backbone` argument to the training script.
