### ISSUE TITLE
AttributeError: 'JPEG' object has no attribute 'decompressor'

### ISSUE THREAD

**Issue by lfydegithub** [open-edge-platform/geti#46]
`WARNING:tensorflow:Can't decode with jpeg4py (libjpeg-turbo): Could not load libjpeg-turbo library. Will use OpenCV.
Exception ignored in: <bound method JPEG.__del__ of <jpeg4py._py.JPEG object at 0x7f0e8962d710>>
Traceback (most recent call last):
  File "/home/lfy/anaconda3/lib/python3.6/site-packages/jpeg4py/_py.py", line 215, in __del__
    if self.decompressor is not None:
AttributeError: 'JPEG' object has no attribute 'decompressor'
`

**Comment by lfydegithub** [comment]
`
INFO:tensorflow:Images without annotation: 24
INFO:tensorflow:[226111, 458790, 461275, 370999, 98497, 228771, 240767, 560371, 330554, 550939, 502910, 127135, 320706, 64574, 198915, 101022, 25593, 528977, 542073, 261796, 312549, 267946, 49091, 447789]
INFO:tensorflow:Using config: {'_model_dir': '/home/lfy/work/training_toolbox_tensorflow-develop/training_toolbox/ssd_detector/coco/model', '_tf_random_seed': 666, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': intra_op_parallelism_threads: 2
inter_op_parallelism_threads: 8
gpu_options {
  per_process_gpu_memory_fraction: 0.9
  allow_growth: true
}
allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 0.1, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f38a676b0b8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2019-02-28 17:55:23.655413: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-02-28 17:55:23.735004: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-02-28 17:55:23.735324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.46GiB
2019-02-28 17:55:23.735338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-02-28 17:55:23.903616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-28 17:55:23.903644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-02-28 17:55:23.903649: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-02-28 17:55:23.903773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5462 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from /home/lfy/work/training_toolbox_tensorflow-develop/training_toolbox/ssd_detector/coco/model/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /home/lfy/work/training_toolbox_tensorflow-develop/training_toolbox/ssd_detector/coco/model/model.ckpt.
WARNING:tensorflow:Can't decode with jpeg4py (libjpeg-turbo): Could not load libjpeg-turbo library. Will use OpenCV.
Exception ignored in: <bound method JPEG.__del__ of <jpeg4py._py.JPEG object at 0x7f3861ef3320>>
Traceback (most recent call last):
  File "/home/lfy/anaconda3/lib/python3.6/site-packages/jpeg4py/_py.py", line 215, in __del__
    if self.decompressor is not None:
AttributeError: 'JPEG' object has no attribute 'decompressor'
`

**Comment by zhou7jing** [comment]
check the environment 
each libraries' version is compatible following the prerequest.txt

**Comment by lfydegithub** [comment]
> check the environment
> each libraries' version is compatible following the prerequest.txt
