### ISSUE TITLE
Unable to complete the training of custom image classification

### ISSUE THREAD

**Issue by Basaveswararaju** [open-edge-platform/geti#642]
Traceback (most recent call last):
  File "/home/kmlubuntu/training_extensions/external/deep-object-reid/tools/main.py", line 178, in <module>
    main()
  File "/home/kmlubuntu/training_extensions/external/deep-object-reid/tools/main.py", line 174, in main
    tb_writer=SummaryWriter(log_dir=log_dir))
  File "/home/kmlubuntu/training_extensions/external/deep-object-reid/torchreid/engine/engine.py", line 434, in run
    should_exit, is_candidate_for_best = self.exit_on_plateau_and_choose_best(top1, top5, mAP)
  File "/home/kmlubuntu/training_extensions/external/deep-object-reid/torchreid/engine/engine.py", line 265, in exit_on_plateau_and_choose_best
    if (round(self.current_lr, 8) <= round(self.lb_lr, 8)):
TypeError: type NoneType doesn't define __round__ method

The above error arises after the first epoch.
I'm not getting the current_lr value.
can anyone please help me out of this?

**Comment by morkovka1337** [comment]
Closing this due to lack of activity.
